spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  application:
    name: EduPortal
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3309/EduPortalDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: stueduportal@gmail.com
    password: ravssxciayvpdgvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# AWS S3 Configuration
file:
  upload-dir: E:/eduPortalStorage/  # Здесь указывается директория для загрузки файлов
cloud:
  aws:
    credentials:
      access-key: AKIAYS2NQTNFCBI2PFGY
      secret-key: 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
    region:
      static: eu-north-1

server:
  port: ${PORT:3000}
